name: Workflow_01
on:
  - push
jobs:
  Wersja_Pythona:
    runs-on: ubuntu-latest
    steps:
      - run: python --version
  Testowanie_w_Pylint:
    runs-on: ubuntu-latest
    steps:
      - run: pip install pylint Flask
      - run: pylint --version
      - run: pylink ./app.py
